
# @no-cookie-jar
GET http://localhost:4000/authorize
Origin: https://test.example.com

> {%
    client.test("Request failed successfully", function() {
        client.assert(response.status === 401, "Response status is correctly set to 401");
    });
%}

<> 2022-05-28T192013.404.txt
<> 2022-05-28T191943.404.txt
<> 2022-05-28T191803.404.txt
<> 2022-05-28T191758.404.txt

###
# @no-redirect
GET http://localhost:4000/authorize
Authorization: Basic alice password
Origin: https://test.example.com

> {%
    client.test("Request authenticated successfully", function() {
        client.assert(response.status === 200, "Response status is correctly set to 200");
    });
%}

###

GET http://localhost:4000/authorize
Origin: https://test.example.com

> {%
    client.test("Request authenticated successfully", function() {
        client.assert(response.status === 200, "Response status is correctly set to 200");
    });
%}