name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.17

      - name: Test
        run: go test -v ./...

  build:

    runs-on: ubuntu-latest
    needs:
      - test
    steps:

    - name: Configure Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Login to Github Packages
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GHCR_PAT }}

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build image and push to Docker Hub and GitHub Container Registry
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          ghcr.io/richard87/forward-basic-auth:latest
          ghcr.io/richard87/forward-basic-auth:${{ github.sha }}


    - name: Image name
      run: echo ghcr.io/richard87/forward-basic-auth:${{ github.sha }}